from __future__ import annotations

from copy import deepcopy

from modules.vehicle_ai.context import (
    ContextManager,
    NavigationState,
)

from modules.vehicle_ai.tools.base import (
    ToolDefinition,
    ToolResult,
)


# ============================================================
# Mock POI database
# ============================================================


MOCK_REST_AREAS = [
    {
        "poi_id":
            "rest_area_001",

        "name":
            "West Lake Rest Area",

        "distance_km":
            6.8,

        "eta_minutes":
            8,
    },

    {
        "poi_id":
            "rest_area_002",

        "name":
            "Riverside Service Area",

        "distance_km":
            12.4,

        "eta_minutes":
            15,
    },
]


# ============================================================
# Navigation Tools
# ============================================================


class NavigationTools:

    def __init__(
        self,
        context_manager: ContextManager,
    ):
        self.context_manager = (
            context_manager
        )

    # ========================================================
    # POI lookup
    # ========================================================

    def _find_poi(
        self,
        poi_id: str,
    ) -> dict | None:

        for poi in MOCK_REST_AREAS:

            if (
                poi["poi_id"]
                == poi_id
            ):

                return deepcopy(
                    poi
                )

        return None

    # ========================================================
    # Search nearby rest area
    # ========================================================

    def search_nearby_rest_area(
        self,
    ) -> ToolResult:
        """
        Mock POI search.

        IMPORTANT:

        poi_id is the canonical execution identity.

        name is only a human-readable display label.
        """

        result = deepcopy(
            MOCK_REST_AREAS[0]
        )

        return ToolResult(
            success=True,
            message=(
                "Nearby rest area found."
            ),
            data=result,
        )

    # ========================================================
    # Start navigation
    # ========================================================

    def start_navigation(
        self,
        poi_id: str,
    ) -> ToolResult:
        """
        Start navigation using a canonical POI identifier.

        Do NOT accept a free-form destination generated by
        the LLM.
        """

        poi_id = (
            poi_id.strip()
        )

        if not poi_id:

            return ToolResult(
                success=False,
                message=(
                    "POI identifier "
                    "cannot be empty."
                ),
                error="EMPTY_POI_ID",
            )

        poi = (
            self._find_poi(
                poi_id
            )
        )

        if poi is None:

            return ToolResult(
                success=False,
                message=(
                    "The requested POI "
                    "could not be resolved."
                ),
                error="UNKNOWN_POI",
                data={
                    "poi_id":
                        poi_id,
                },
            )

        self.context_manager.update_vehicle(
            navigation_destination_id=(
                poi["poi_id"]
            ),
            navigation_destination=(
                poi["name"]
            ),
            navigation_state=(
                NavigationState.ACTIVE
            ),
        )

        return ToolResult(
            success=True,
            message=(
                "Navigation started to "
                f"'{poi['name']}'."
            ),
            data={
                "poi_id":
                    poi["poi_id"],

                "destination":
                    poi["name"],

                "distance_km":
                    poi["distance_km"],

                "eta_minutes":
                    poi["eta_minutes"],

                "navigation_state":
                    NavigationState.ACTIVE,
            },
        )

    # ========================================================
    # Cancel navigation
    # ========================================================

    def cancel_navigation(
        self,
    ) -> ToolResult:

        self.context_manager.update_vehicle(
            navigation_destination_id=None,
            navigation_destination=None,
            navigation_state=(
                NavigationState.IDLE
            ),
        )

        return ToolResult(
            success=True,
            message=(
                "Navigation cancelled."
            ),
            data={
                "navigation_state":
                    NavigationState.IDLE,
            },
        )


# ============================================================
# Registration
# ============================================================


def build_navigation_tools(
    context_manager: ContextManager,
) -> list[ToolDefinition]:

    tools = NavigationTools(
        context_manager
    )

    return [
        ToolDefinition(
            name=(
                "search_nearby_rest_area"
            ),
            description=(
                "Find a nearby rest area "
                "where the driver can stop "
                "and rest. "
                "The result includes a "
                "canonical poi_id which "
                "must be used for navigation."
            ),
            category="navigation",
            parameters={
                "type": "object",
                "properties": {},
                "required": [],
                "additionalProperties":
                    False,
            },
            handler=(
                tools
                .search_nearby_rest_area
            ),
        ),

        ToolDefinition(
            name="start_navigation",
            description=(
                "Start navigation to a "
                "previously resolved POI. "
                "Use the exact canonical "
                "poi_id returned by a search "
                "tool or pending action. "
                "Never translate, rewrite, "
                "or invent the poi_id."
            ),
            category="navigation",
            parameters={
                "type": "object",
                "properties": {
                    "poi_id": {
                        "type": "string",
                        "description": (
                            "Canonical POI ID "
                            "returned by a "
                            "search tool, for "
                            "example "
                            "'rest_area_001'."
                        ),
                    },
                },
                "required": [
                    "poi_id"
                ],
                "additionalProperties":
                    False,
            },
            handler=(
                tools.start_navigation
            ),
            requires_confirmation=True,
        ),

        ToolDefinition(
            name="cancel_navigation",
            description=(
                "Cancel the active "
                "navigation session."
            ),
            category="navigation",
            parameters={
                "type": "object",
                "properties": {},
                "required": [],
                "additionalProperties":
                    False,
            },
            handler=(
                tools.cancel_navigation
            ),
            requires_confirmation=True,
        ),
    ]